### ISSUE TITLE
Consistent hash can get out of sync with JGroups

### ISSUE THREAD

**Issue by sgrimm-sg** [AxonFramework/extension-jgroups#2]
This is pretty obscure, but bit us thanks to an AWS problem that caused one of our EC2 instances to get suspended for a couple minutes then wake up unaware that anything had happened. We saw it on Axon 2.4.5 but it seems like Axon 3 would behave the same. I believe this could also happen due to network outages if the timing is just right.

The sequence:

1. Nodes A and B are in a JGroups cluster with a distributed command bus.
2. A goes to sleep or loses network connectivity.
3. B times out waiting for A to respond to heartbeats, and marks A as dead. `JGroupsConnector` removes A from the consistent hash.
4. A wakes up or, in the case of a network issue, regains network connectivity before the JGroups timer that checks for missing heartbeats would have fired for the last time.
5. At this point, A thinks it is in a cluster [A,B] and B thinks it is in a cluster [B].
6. JGroups discovery runs, and B discovers that A is alive. The JGroups view on B is updated.
7. B sends a `JoinMessage` to A, advertising the commands it can handle.
8. A receives the message. Since it had never removed B from its consistent hash, the hash doesn't change as a result of the message.
9. At this point, JGroups on both nodes thinks the cluster is [A,B]. The consistent hash on A has entries for A and B. But since A has had no reason to send a `JoinMessage` to B, the consistent hash on B only has entries for B.

The inconsistency remains until the application is restarted on one of the hosts.

The fix I came up with is to intercept the incoming `JoinMessage` and attempt to apply it to the local consistent hash. If the hash is the same before and after applying the data from the message, I send a `JoinMessage` in response. (Actually I send a subclass of `JoinMessage`, to avoid the risk of two nodes bouncing redundant messages back and forth forever.)

In the above example, that'd be triggered in step 8 and would cause node A to send a `JoinMessage` (subclass instance) back to node B, which would cause both nodes to have the same consistent hash.

**Comment by abuijze** [comment]
I have a strong feeling this issue has been fixed as part of some other issues. Looking at the code, nodes that send their configuration to another request a JoinMessage in return. In your scenario, this would cause node B to send a JoinMessage to A, requesting a reply. Node A will always send a message back, with the "expectReply" flag set to false to prevent bouncing.

If you have a chance to validate that assumption, that would be great. I'm not sure how to simulate this, just yet.

**Comment by sgrimm-sg** [comment]
I won't be able to test this until our application is ported to Axon 4, which is underway now but still a little while off.

If I remember correctly, I simulated this in my development environment by running a two-node cluster and then suspending one of the two Java processes, waiting for the remaining one to time out waiting for heartbeats and remove the suspended one from its cluster, and then resuming the suspended process.

**Comment by sgrimm-sg** [comment]
I can't reproduce this in the Axon 4 version of our application, so it seems like it is indeed fixed. Closing the issue.
