### ISSUE TITLE
Set Exception Details in Command Result

### ISSUE THREAD

**Issue by smcvb** [AxonFramework/extension-jgroups#3]
In issue [#1079](https://github.com/AxonFramework/AxonFramework/issues/1079), the option was introduced to add application specific exception details back to another node.
The Spring Cloud extension should be adapted to utilize this mechanic too.

**Comment by abuijze** [comment]
Addressed in AxonFramework (https://github.com/AxonFramework/AxonFramework/pull/1192)

**Comment by sgrimm-sg** [comment]
With the change in the framework, I'm now getting `CommandExecutionException` in my command callbacks, but it wraps the same `RemoteHandlingException` the callbacks used to get, and the application-specific exception details aren't present there.

**Comment by smcvb** [comment]
This behaviour is correct @sgrimm-sg. 
The idea is that an Axon client application can throw a [`CommandExecutionException`](https://github.com/AxonFramework/AxonFramework/blob/master/messaging/src/main/java/org/axonframework/commandhandling/CommandExecutionException.java) where you can provide your own set of details to be more specific with the actual exception being thrown.

Deserializing the actual exception being thrown on one end is doable in scenarios where both nodes are identical, but isn't when you have different application with different code bases. Hence why specifying the details is done through this format.

I've a pending issue to be more specific about this in the Reference Guide too, as your question is definitely valid.
